INSERT INTO users (nick, name)
VALUES ('qwerty111', 'Petrovich'),
       ('kokoko123', 'Fridrih'),
       ('azino777', 'Sergey'),
       ('sdfgldmkn12345', 'Kdknvf'),
       ('fgh5365', 'DedPihto');

INSERT INTO chats (is_group_chat, topic)
VALUES (FALSE, 'P-F'),
       (FALSE, 'F-S'),
       (FALSE, 'S-K'),
       (FALSE, 'K-D'),
       (FALSE, 'D-P');

INSERT INTO messages (chat_id, user_id)
VALUES (1, 1),
       (1, 1),
       (1, 1),
       (1, 1),
       (1, 1),
       (1, 2),
       (1, 2),
       (1, 2),
       (1, 2),
       (1, 2),
       (2, 2),
       (2, 2),
       (2, 2),
       (2, 2),
       (2, 2),
       (2, 3),
       (2, 3),
       (2, 3),
       (2, 3),
       (2, 3),
       (3, 3),
       (3, 3),
       (3, 3),
       (3, 3),
       (3, 3),
       (3, 4),
       (3, 4),
       (3, 4),
       (3, 4),
       (3, 4),
       (4, 4),
       (4, 4),
       (4, 4),
       (4, 4),
       (4, 4),
       (4, 5),
       (4, 5),
       (4, 5),
       (4, 5),
       (4, 5),
       (5, 5),
       (5, 5),
       (5, 5),
       (5, 5),
       (5, 5),
       (5, 1),
       (5, 1),
       (5, 1),
       (5, 1),
       (5, 1);

INSERT INTO members (user_id, chat_id, last_read_message_id)
VALUES (1, 1, NULL),
       (2, 1, NULL),
       (2, 2, NULL),
       (3, 2, NULL),
       (3, 3, NULL),
       (4, 3, NULL),
       (4, 4, NULL),
       (5, 4, NULL),
       (5, 5, NULL),
       (1, 5, NULL);

INSERT INTO attachs (message_id, data)
VALUES (1, 'Hello'),
       (2, 'Hello'),
       (3, 'Hello'),
       (4, 'Hello'),
       (5, 'Hello'),
       (6, 'Hello'),
       (7, 'Hello'),
       (8, 'Hello'),
       (9, 'Hello'),
       (10, 'Hello'),
       (11, 'Hello'),
       (12, 'Hello'),
       (13, 'Hello'),
       (14, 'Hello'),
       (15, 'Hello'),
       (16, 'Hello'),
       (17, 'Hello'),
       (18, 'Hello'),
       (19, 'Hello'),
       (20, 'Hello'),
       (21, 'Hello'),
       (22, 'Hello'),
       (23, 'Hello'),
       (24, 'Hello'),
       (25, 'Hello'),
       (26, 'Hello'),
       (27, 'Hello'),
       (28, 'Hello'),
       (29, 'Hello'),
       (30, 'Hello'),
       (31, 'Hello'),
       (32, 'Hello'),
       (33, 'Hello'),
       (34, 'Hello'),
       (35, 'Hello'),
       (36, 'Hello'),
       (37, 'Hello'),
       (38, 'Hello'),
       (39, 'Hello'),
       (40, 'Hello'),
       (41, 'Hello'),
       (42, 'Hello'),
       (43, 'Hello'),
       (44, 'Hello'),
       (45, 'Hello'),
       (46, 'Hello'),
       (47, 'Hello'),
       (48, 'Hello'),
       (49, 'Hello'),
       (50, 'Hello');








